import {
  ServiceOption,
  ServicePricingConfig,
  ServicePricingMode,
} from "../types/domain";

export interface DefaultServiceInput {
  title: string;
  slug: string;
  description?: string | null;
  imageUrl?: string | null;
  isActive: boolean;
  sortOrder: number;
  basePrice: number;
  priceUnit?: string | null;
  pricingMode: ServicePricingMode;
  pricingConfig: ServicePricingConfig;
  options: ServiceOption[];
  expectations: string[];
  categorySlug?: string;
}

const DEFAULT_VAT_RATE = 0.05;

const maidRecurringOptions = [
  { value: "one-time", label: "One Time", visitsPerMonth: 1, discountPercent: 0 },
  { value: "weekly", label: "Once a Week", visitsPerMonth: 4, discountPercent: 5 },
  { value: "2-times-weekly", label: "Twice a Week", visitsPerMonth: 8, discountPercent: 10 },
  { value: "3-times-weekly", label: "3 Times a Week", visitsPerMonth: 12, discountPercent: 15 },
  { value: "4-times-weekly", label: "4 Times a Week", visitsPerMonth: 16, discountPercent: 15 },
  { value: "5-times-weekly", label: "5 Times a Week", visitsPerMonth: 20, discountPercent: 15 },
  { value: "6-times-weekly", label: "6 Times a Week", visitsPerMonth: 24, discountPercent: 15 },
  { value: "bi-weekly", label: "Every Other Week", visitsPerMonth: 2, discountPercent: 5 },
  { value: "every-3-weeks", label: "Every 3 Weeks", visitsPerMonth: 4 / 3, discountPercent: 5 },
  { value: "every-4-weeks", label: "Every 4 Weeks", visitsPerMonth: 1, discountPercent: 5 },
  { value: "every-5-weeks", label: "Every 5 Weeks", visitsPerMonth: 0.8, discountPercent: 5 },
  { value: "every-6-weeks", label: "Every 6 Weeks", visitsPerMonth: 2 / 3, discountPercent: 5 },
];

export const DEFAULT_SERVICES: DefaultServiceInput[] = [
  {
    title: "House Cleaning Services",
    slug: "maid-cleaning",
    imageUrl: "/hero-cleaning.jpg",
    isActive: true,
    categorySlug: "cleaning",
    sortOrder: 10,
    basePrice: 35,
    priceUnit: "/hr",
    pricingMode: "hourly",
    pricingConfig: {
      vatRate: DEFAULT_VAT_RATE,
      hourly: {
        rate: 35,
        hoursOptionId: "hours",
        staffCountOptionId: "crew",
      },
      recurring: {
        enabled: true,
        frequencyOptionId: "frequency",
        options: maidRecurringOptions,
      },
    },
    expectations: [
      "Dusting and wiping surfaces",
      "Floor mopping and vacuuming",
      "Furniture cleaning and polishing",
      "Arranging bedsheets and tidying up",
      "General kitchen and bathroom cleaning",
    ],
    options: [
      {
        id: "frequency",
        label: "Select your booking frequency (offers for recurring bookings)",
        type: "select",
        options: maidRecurringOptions.map(({ label, value }) => ({ label, value })),
        defaultValue: "one-time",
      },
      {
        id: "crew",
        label: "Number of cleaners (35 AED/hr each)",
        type: "quantity",
        defaultValue: 1,
        min: 1,
      },
      {
        id: "hours",
        label: "Hours",
        type: "quantity",
        defaultValue: 4,
        min: 2,
      },
      {
        id: "extras",
        label: "Extras",
        type: "checkbox",
        options: [
          { label: "Cleaning supplies (+10 AED)", value: "supplies", price: 10 },
        ],
        defaultValue: [],
      },
    ],
  },
  {
    title: "Sofa Cleaning Service",
    slug: "sofa-cleaning-service",
    imageUrl: "/hero-cleaning.jpg",
    isActive: true,
    categorySlug: "cleaning",
    sortOrder: 20,
    basePrice: 0,
    priceUnit: "based on selection",
    pricingMode: "quantity",
    pricingConfig: { vatRate: DEFAULT_VAT_RATE },
    expectations: [
      "Deep vacuuming to remove dust and allergens",
      "Shampooing (wet/dry based on fabric) treatment",
      "Stain removal and spot treatment",
      "Sanitization and deodorizing",
      "Fabric protection layer (optional add-on)",
    ],
    options: [
      {
        id: "frequency",
        label: "Select your booking frequency",
        type: "radio",
        options: [{ label: "One-time", value: "one-time" }],
        defaultValue: "one-time",
      },
      { id: "single-seater", label: "Single Seater Sofa (50 AED/seat)", type: "quantity", price: 50, defaultValue: 0 },
      { id: "two-seater", label: "2-Seater Sofa (100 AED)", type: "quantity", price: 100, defaultValue: 0 },
      { id: "three-seater", label: "3-Seater Sofa (150 AED)", type: "quantity", price: 150, defaultValue: 0 },
    ],
  },
  {
    title: "Rug / Carpet Cleaning",
    slug: "rug-carpet-cleaning",
    imageUrl: "/hero-cleaning.jpg",
    isActive: true,
    categorySlug: "cleaning",
    sortOrder: 30,
    basePrice: 0,
    priceUnit: "based on selection",
    pricingMode: "quantity",
    pricingConfig: { vatRate: DEFAULT_VAT_RATE },
    expectations: [
      "Pre-inspection and spot testing",
      "Deep vacuuming",
      "Hot water extraction or dry cleaning",
      "Stain and spot removal",
      "Grooming and drying",
    ],
    options: [
      {
        id: "frequency",
        label: "Select your booking frequency",
        type: "radio",
        options: [{ label: "One-time", value: "one-time" }],
        defaultValue: "one-time",
      },
      { id: "small-rug", label: "Small Rug / Carpet (1.5 x 2.4m) - 149 AED", type: "quantity", price: 149, defaultValue: 0 },
      { id: "medium-rug", label: "Medium Rug / Carpet (2.4 x 3m) - 199 AED", type: "quantity", price: 199, defaultValue: 0 },
      { id: "large-rug", label: "Large Rug / Carpet (3 x 4.3m) - 299 AED", type: "quantity", price: 299, defaultValue: 0 },
    ],
  },
  {
    title: "Painting Services",
    slug: "painting",
    description: "Scope includes protection, sanding, priming, 2-3 coats.",
    imageUrl: "/hero-cleaning.jpg",
    isActive: true,
    categorySlug: "renovation",
    sortOrder: 40,
    basePrice: 699,
    priceUnit: "starting from",
    pricingMode: "package",
    pricingConfig: { vatRate: DEFAULT_VAT_RATE },
    expectations: [
      "Furniture and floor covering/protection",
      "Surface preparation (sanding, filling cracks)",
      "Priming of walls where necessary",
      "Application of 2-3 coats of premium paint",
      "Post-service cleanup",
    ],
    options: [
      {
        id: "service-type",
        label: "Service Type",
        type: "select",
        options: [
          { label: "Studio Apartment (699 AED)", value: "studio", price: 699 },
          { label: "1 BHK Apartment (899 AED)", value: "1bhk-apt", price: 899 },
          { label: "2 BHK Apartment (1399 AED)", value: "2bhk-apt", price: 1399 },
          { label: "3 BHK Apartment (1999 AED)", value: "3bhk-apt", price: 1999 },
          { label: "4 BHK Apartment (2500 AED)", value: "4bhk-apt", price: 2500 },
          { label: "5 BHK Apartment (3300 AED)", value: "5bhk-apt", price: 3300 },
          { label: "1 BHK Villa (1499 AED)", value: "1bhk-villa", price: 1499 },
          { label: "3 BHK Villa (2899 AED)", value: "3bhk-villa", price: 2899 },
          { label: "4 BHK Villa (3699 AED)", value: "4bhk-villa", price: 3699 },
        ],
        defaultValue: "studio",
      },
      {
        id: "door-painting",
        label: "Door Painting Add-ons",
        type: "checkbox",
        options: [
          { label: "Roller (500 AED/door)", value: "roller", price: 500 },
          { label: "Spray (650 AED/door)", value: "spray", price: 650 },
          { label: "PU Paint (750 AED/door)", value: "pu", price: 750 },
        ],
        defaultValue: [],
      },
    ],
  },
  {
    title: "Kitchen Deep Cleaning",
    slug: "kitchen-deep-cleaning",
    imageUrl: "/hero-cleaning.jpg",
    isActive: true,
    categorySlug: "cleaning",
    sortOrder: 50,
    basePrice: 199,
    priceUnit: "starting from",
    pricingMode: "package",
    pricingConfig: { vatRate: DEFAULT_VAT_RATE },
    expectations: [
      "Degreasing of hood and stovetop",
      "Internal and external cabinet cleaning",
      "Appliance cleaning (fridge, oven, microwave)",
      "Sink descaling and sanitization",
      "Floor scrubbing and grout cleaning",
    ],
    options: [
      {
        id: "size",
        label: "Kitchen Size",
        type: "select",
        options: [
          { label: "Small - Premium (199 AED)", value: "small-premium", price: 199 },
          { label: "Small - Full Scrub (249 AED)", value: "small-full", price: 249 },
          { label: "Medium - Premium (249 AED)", value: "medium-premium", price: 249 },
          { label: "Medium - Full Scrub (299 AED)", value: "medium-full", price: 299 },
          { label: "Large - Premium (299 AED)", value: "large-premium", price: 299 },
          { label: "Large - Full Scrub (349 AED)", value: "large-full", price: 349 },
        ],
        defaultValue: "small-premium",
      },
    ],
  },
  {
    title: "Deep Cleaning Services",
    slug: "deep-cleaning",
    imageUrl: "/hero-cleaning.jpg",
    isActive: true,
    categorySlug: "cleaning",
    sortOrder: 60,
    basePrice: 399,
    priceUnit: "starting from",
    pricingMode: "package",
    pricingConfig: { vatRate: DEFAULT_VAT_RATE },
    expectations: [
      "Comprehensive cleaning of all rooms",
      "Deep scrubbing of floors and tiles",
      "Window and balcony cleaning",
      "Disinfection of bathrooms and kitchen",
      "Cleaning of light fixtures and vents",
    ],
    options: [
      {
        id: "type",
        label: "Service Type",
        type: "select",
        options: [
          { label: "Studio (399 AED)", value: "studio", price: 399 },
          { label: "1 BHK Apt (549 AED)", value: "1bhk-apt", price: 549 },
          { label: "2 BHK Apt (649 AED)", value: "2bhk-apt", price: 649 },
          { label: "3 BHK Apt (749 AED)", value: "3bhk-apt", price: 749 },
          { label: "4 BHK Apt (899 AED)", value: "4bhk-apt", price: 899 },
          { label: "2 BHK Villa (899 AED)", value: "2bhk-villa", price: 899 },
          { label: "3 BHK Villa (1199 AED)", value: "3bhk-villa", price: 1199 },
          { label: "4 BHK Villa (1499 AED)", value: "4bhk-villa", price: 1499 },
          { label: "5 BHK Villa (1799 AED)", value: "5bhk-villa", price: 1799 },
          { label: "Small Bathroom Deep Cleaning (199 AED)", value: "small-bathroom", price: 199 },
          { label: "Large Bathroom / Master Deep Cleaning (249 AED)", value: "large-bathroom", price: 249 },
        ],
        defaultValue: "studio",
      },
    ],
  },
  {
    title: "Commercial / Office Deep Cleaning",
    slug: "commercial-deep-cleaning",
    imageUrl: "/hero-cleaning.jpg",
    isActive: true,
    categorySlug: "cleaning",
    sortOrder: 70,
    basePrice: 0,
    priceUnit: "per sqm",
    pricingMode: "area",
    pricingConfig: { vatRate: DEFAULT_VAT_RATE },
    expectations: [
      "Workstation and desk sanitization",
      "Carpet vacuuming and floor polishing",
      "Glass partition and window cleaning",
      "Kitchenette and restroom deep cleaning",
      "Trash removal and bin sanitization",
    ],
    options: [
      { id: "area-size", label: "Area Size (SQM) - 10 AED/SQM", type: "quantity", price: 10, defaultValue: 50 },
    ],
  },
  {
    title: "Limewash Texture Painting",
    slug: "limewash-painting",
    imageUrl: "/hero-cleaning.jpg",
    isActive: true,
    categorySlug: "renovation",
    sortOrder: 80,
    basePrice: 0,
    priceUnit: "per sqm",
    pricingMode: "area",
    pricingConfig: { vatRate: DEFAULT_VAT_RATE },
    expectations: [
      "Surface priming with specialized primer",
      "Application of first limewash coat (criss-cross motion)",
      "Second coat application for texture depth",
      "Final detailing and touch-ups",
      "Sealing (optional for high traffic areas)",
    ],
    options: [
      { id: "area-size", label: "Total Area (SQM) - 115 AED/SQM", type: "quantity", price: 115, defaultValue: 10 },
    ],
  },
  {
    title: "Mattress Cleaning Service",
    slug: "mattress-cleaning",
    imageUrl: "/hero-cleaning.jpg",
    isActive: true,
    categorySlug: "cleaning",
    sortOrder: 90,
    basePrice: 99,
    priceUnit: "starting from",
    pricingMode: "quantity",
    pricingConfig: { vatRate: DEFAULT_VAT_RATE },
    expectations: [
      "High-power UV vacuuming for dust mites",
      "Steam cleaning for deep sanitation",
      "Stain pre-treatment and removal",
      "Moisture extraction",
      "Eco-friendly anti-allergen spray",
    ],
    options: [
      { id: "single-mattress", label: "Single Mattress (99 AED)", type: "quantity", price: 99, defaultValue: 0 },
      { id: "queen-mattress", label: "Queen Mattress (149 AED)", type: "quantity", price: 149, defaultValue: 0 },
      { id: "king-mattress", label: "King Mattress (199 AED)", type: "quantity", price: 199, defaultValue: 0 },
    ],
  },
  {
    title: "AC Services",
    slug: "ac-services",
    imageUrl: "/hero-cleaning.jpg",
    isActive: true,
    categorySlug: "maintenance",
    sortOrder: 100,
    basePrice: 0,
    priceUnit: "based on selection",
    pricingMode: "package",
    pricingConfig: { vatRate: DEFAULT_VAT_RATE },
    expectations: [
      "Filter cleaning and full airflow check",
      "Coil and drain line cleaning",
      "Cooling performance and thermostat testing",
      "Minor leak/issue diagnostics",
      "Post-service testing and report",
    ],
    options: [
      {
        id: "service-type",
        label: "Select AC Service Type",
        type: "select",
        options: [
          { label: "AC General Service (149 AED)", value: "ac-general-service", price: 149 },
          { label: "AC Deep Cleaning (249 AED)", value: "ac-deep-cleaning", price: 249 },
          { label: "AC Gas Top-Up (299 AED)", value: "ac-gas-top-up", price: 299 },
          { label: "AC Inspection / Diagnosis (99 AED)", value: "ac-inspection", price: 99 },
        ],
        defaultValue: "ac-general-service",
      },
    ],
  },
  {
    title: "Renovation Services",
    slug: "renovation-services",
    imageUrl: "/hero-cleaning.jpg",
    isActive: true,
    categorySlug: "renovation",
    sortOrder: 110,
    basePrice: 1000,
    priceUnit: "starting from",
    pricingMode: "package",
    pricingConfig: { vatRate: DEFAULT_VAT_RATE },
    expectations: [
      "Initial site survey and consultation",
      "Material selection and procurement",
      "Demolition and debris removal (if required)",
      "Installation/Construction works",
      "Final finishing and quality inspection",
    ],
    options: [
      {
        id: "frequency",
        label: "Select your booking frequency",
        type: "select",
        options: [{ label: "One Time", value: "one-time" }],
        defaultValue: "one-time",
      },
      { id: "hours", label: "How many Hours? (200 AED/hr)", type: "quantity", price: 200, defaultValue: 5, min: 2 },
    ],
  },
  {
    title: "Moulding Services",
    slug: "moulding-services",
    imageUrl: "/hero-cleaning.jpg",
    isActive: true,
    categorySlug: "renovation",
    sortOrder: 120,
    basePrice: 450,
    priceUnit: "starting from",
    pricingMode: "package",
    pricingConfig: { vatRate: DEFAULT_VAT_RATE },
    expectations: [
      "Measurement and design planning",
      "Cutting and preparation of moulding trims",
      "Precision installation and fixing",
      "Caulking and filling gaps",
      "Final painting or finishing of trims",
    ],
    options: [
      {
        id: "service-type",
        label: "Service Type",
        type: "select",
        options: [{ label: "Moulding Trim Services (Starting 450 AED)", value: "trim", price: 450 }],
        defaultValue: "trim",
      },
      {
        id: "frequency",
        label: "Select your booking frequency",
        type: "select",
        options: [{ label: "One Time", value: "one-time" }],
        defaultValue: "one-time",
      },
      { id: "hours", label: "Duration (Hours) - 100 AED/hr", type: "quantity", price: 100, defaultValue: 2, min: 2 },
    ],
  },
];
